package p2.p2;

import java.util.List;

import p2.p2.SimulationEvent;



/**
 * Validates a simulation
 */
public class Validate {
	private static class InvalidSimulationException extends Exception {
		public InvalidSimulationException() { }
	};

	// Helper method for validating the simulation
	private static void check(boolean check,
			String message) throws InvalidSimulationException {
		if (!check) {
			System.err.println("SIMULATION INVALID : "+message);
			throw new Validate.InvalidSimulationException();
		}
	}

	/** 
	 * Validates the given list of events is a valid simulation.
	 * Returns true if the simulation is valid, false otherwise.
	 *
	 * @param events - a list of events generated by the simulation
	 *   in the order they were generated.
	 *
	 * @returns res - whether the simulation was valid or not
	 */
	public static boolean validateSimulation(List<SimulationEvent> events,int numCustomers, int numCooks, int numTables, int machineCapacity) {
		try {
			check(events.get(0).event == SimulationEvent.EventType.SimulationStarting,
					"Simulation didn't start with initiation event");
			check(events.get(events.size()-1).event == 
					SimulationEvent.EventType.SimulationEnded,
					"Simulation didn't end with termination event");
			
			
			
			check(caffeCapacityCheck(events,numTables),"Number of customers exceeds the number of tables in caffe");
			

			/* In P2 you will write validation code for things such as:
				Should not have more eaters than specified
				
				
				Should not have more cooks than specified
				The coffee shop capacity should not be exceeded
				The capacity of each machine should not be exceeded
				Eater should not receive order until cook completes it
				Eater should not leave coffee shop until order is received
				Eater should not place more than one order
				Cook should not work on order before it is placed
			 */

			return true;
		} catch (InvalidSimulationException e) {
			return false;
		}
	}
	
	private static boolean caffeCapacityCheck(
			List<SimulationEvent> events, int numTables) {
		boolean result = true;
		int currNumCustomers = 0;
		// Max Customers Test
		for (SimulationEvent e : events) {
			if (e.event == SimulationEvent.EventType.CustomerEnteredCoffeeShop) {
				currNumCustomers++;
			}
			if (e.event == SimulationEvent.EventType.CustomerLeavingCoffeeShop) {
				currNumCustomers--;
			}
			if (currNumCustomers > numTables) {
				result = false;
			}
		}
		return result;
	}
}
